#!usr/bin/env python3
#-*- coding:utf-8 -*-
#Başlangıç 22.11.2023 20:20
#Bitiş -:-
import os
os.system("clear")
os.system("pkg install figlet")
os.system('clear')
os.system ("figlet KanliSilah")
print("#Codded by Hacker KanlıSilah and Hacker Banu")
print("\nHoş gəldiniz sizin üçün nə edə bilərəm. \n \n 1. Bütün paketləri yüklə.")
a = input(str("\nSeçiminiz:"))
if a == "1":
    print("Lazımlı paketlər yüklənir. Xaiş olunur gözləyin, bu sizin internet bağlantınızın surətindən asılı olaraq vaxt apara bilər")
    print("8")
    os.system("sleep 1")
    print("7")
    os.system("sleep 1")
    print("6")
    os.system("sleep 1")
    print("5")
    os.system("sleep 1")
    print("4")
    os.system("sleep 1")
    print("3")
    os.system("sleep 1")
    print("2")
    os.system("sleep 1")
    print("1")
    print("Diqqət yükləmə başlayır")
    os.system("pkg install git -y")
    os.system("pkg install python -y")
    os.system("pkg install python2 -y")
    os.system("pkg install python3 -y")
    os.system("pkg install bash -y")
    os.system("pkg install curl -y ")
    os.system("pkg install php -y")
    os.system("pkg install perl -y")
    os.system("pkg install busybox -y")
    os.system("pkg install cmatrix -y")
    os.system("pkg install dnsutils -y")
    os.system("pkg install hashdeep -y")
    os.system("pkg install hexcurse -y")
    os.system("pkg install json-c -y")
    os.system("pkg install openssl -y")
    os.system("pkg install sslscan -y")
    os.system("pkg install unzip -y")
    os.system("pkg install nmap -y")
    os.system("pkg install termux-tools -y")
    os.system("pkg install wget -y")
    os.system("pkg install root-repo")
    os.system("pkg install x11-repo")
    os.system("pkg install tur-repo")
    os.system("apt update -y")
    os.system('pip install pyfiglet')
    os.system('pip install selenium')
    os.system('pip install requests')
    os.system('pip install pyfiglet')
    os.system('pip install sys')
    os.system('pip install py_compile')
    os.system('pip install youtube_dl')
    os.system('pip install uuid')
    os.system('pip install time')
    os.system('pip install os')
    os.system('pip install random')
    os.system('pip install datetime')
    os.system('pip install string')
    os.system('pip install secrets')
    os.system('pip install webbrowser')
    os.system('pip install hashlib')
    os.system('pip install colorama')
    os.system('pip install n')
    os.system('pip install mm')
    os.system('pip install new')
    os.system('pip install sleep')
    os.system('pip install BeautifulSoup')
    os.system('pip install new')
    os.system('pip install pafy')
    os.system('pip install bs4')
    os.system('pip install sys')
    os.system('pip install json')
    os.system('pip install random')
    os.system('pip install uuid')
    os.system('pip install secrets')
    os.system('pip install datetime')
    os.system('pip install argparse')
    os.system('pip install InstagramAPI')
    os.system('pip install sleep')
    os.system('pip install string')
    os.system('pip install uuid4')
    os.system('pip install generate_user_agent')
    os.system('pip install threading')
    os.system('pip install json')
    os.system('pip install datetime')
    os.system('pip install token_hex')
    os.system('pip install secrets')
    os.system('pip install token_hex')
    os.system('pip install Fore')
    os.system('pip install secrets')
    os.system('pip install uuid')
    os.system('pip install re')
    os.system('pip install b')
    os.system('pip install requests')
    os.system('pip install pyfiglet')
    os.system('pip install sys')
    os.system('pip install py_compile')
    os.system('pip install youtube_dl')
    os.system('pip install uuid')
    os.system('pip install time')
    os.system('pip install os')
    os.system('pip install random')
    os.system('pip install datetime')
    os.system('pip install string')
    os.system('pip install secrets')
    os.system('pip install webbrowser')
    os.system('pip install hashlib')
    os.system('pip install colorama')
    os.system('pip install n')
    os.system('pip install mm')
    os.system('pip install new')
    os.system('pip install sleep')
    os.system('pip install BeautifulSoup')
    os.system('pip install new')
    os.system('pip install pafy')
    os.system('pip install bs4')
    os.system('pip install sys')
    os.system('pip install json')
    os.system('pip install random')
    os.system('pip install uuid')
    os.system('pip install secrets')
    os.system('pip install datetime')
    os.system('pip install *')
    os.system('pip install argparse')
    os.system('pip install InstagramAPI')
    os.system('pip install sleep')
    os.system('pip install string')
    os.system('pip install uuid4')
    os.system('pip install generate_user_agent')
    os.system('pip install threading')
    os.system('pip install json')
    os.system('pip install datetime')
    os.system('pip install token_hex')
    os.system('pip install secrets')
    os.system('pip install token_hex')
    os.system('pip install Fore')
    os.system('pip install secrets')
    os.system('pip install uuid')
    os.system('pip install re')
    os.system('pip install b')
    os.system('pip install telethon')
    os.system('pip install pyshorteners')
    os.system('pip install finite_state_machine')
    os.system('cls' if os.name == 'nt' else 'clear') 
    os.system("apt upgrade -y")
    os.system("pkg update -y && pkg upgrade -y")
else:
    print("Yalnış seçim!!")
    os.system("python kanli.py")